# mysql
spring.datasource.druid.url=jdbc:mysql://192.168.197.129:3306/education_course?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.druid.username=root
spring.datasource.druid.password=UYbFDTPcsAOE1kYnCSr+O1+CfW5Y5pucyn8dWfYXvLjXfuvXgILA87lSmeiP3/4Q9h4XwUTVVi9ED+exeq1xZw==
spring.datasource.druid.filters=config
spring.datasource.druid.connection-properties=config.decrypt=true

swagger.enabled=true
